version: "3.8"

services:
    database_test:
        image: postgres:15.1-alpine
        container_name: postgres_test
        restart: always
        environment:
              POSTGRES_PASSWORD: admin
              POSTGRES_USER: admin
              POSTGRES_DB: test_db
              POSTGRES_INITDB_ARGS: "-A md5"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin -d admin" ]
            interval: 5s
            timeout: 10s
            retries: 10
            start_period: 10s
        ports:
            - "5432:5433"
    web_app_test:
        build:
            context: ../../
            dockerfile: ./docker/application/Dockerfile
        container_name: django_test
        ports:
            - "8001:8001"
        depends_on:
            database_test:
                condition: service_healthy
            redis_test:
                condition: service_healthy
        volumes:
            - ../../src:/file_processing
        command: > 
            sh -c "python manage.py test"
    redis_test:
        image: redis:7.2-alpine
        hostname: redis
        container_name: redis_test
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 10s
            retries: 10